### ISSUE TITLE
Add --help

### ISSUE THREAD

**Issue by dodekeract** [yamafaktory/shrimpit#10]
Would be nice if the de facto standard `--help` would be implemented, users (at least me!) expect it to work. 🙂

**Comment by yamafaktory** [comment]
Hi @dodekeract,

Thank you for the feedback! I'll do it 👍

**Comment by yamafaktory** [comment]
@dodekeract the `--help` flag is now available and unknown flags are also handled (with a fallback to help of course) 🍻. I close the issue, feel free to reopen a new one if this is not matching your expectations!
