### ISSUE TITLE
Re-exports support

### ISSUE THREAD

**Issue by angly-cat** [yamafaktory/shrimpit#102]
Hi!
Great lib! However it doesn't handle re-exports properly. For example:
```
// a.js
export const a1 = {};
export const a2 = {};
```
```
// b.js
export * from "./a";
```
```
// c.js
import { a1 } from "./b";
```
These files would produce:
```
 Shrimpit!  

 > Unused exports  

[ { location: 'test/a.js', name: 'a1', unnamedDefault: false },
  { location: 'test/a.js', name: 'a2', unnamedDefault: false } ]
```
However, only `a2` is unused.

Would you please support re-exports?

**Comment by yamafaktory** [comment]
@angly-cat I've have been working on a new branch to fix the issues with re-exporting. I'll try to have it available this week.

**Comment by yamafaktory** [comment]
@angly-cat a little update: I should have covered all those re-exports properly now (adding some more complexity of course), you can see it in this branch https://github.com/yamafaktory/shrimpit/tree/re-export. I need to do some cleanup and extend the unit tests and then I'll merge it.
