### ISSUE TITLE
Work with UMD?

### ISSUE THREAD

**Issue by franciscop** [yamafaktory/shrimpit#127]
Hi, is it possible to use this with UMD? (Universal Module Definition). As an example [with my library Ola](), when I try it on the minified code I get:

```
 Shrimpit!  

[]
 > Unused exports  
```

However, if I remove the headers and use the `export default` I get the correct:

```js
[ { location: 'data/ola.js',
    name: 'default (unnamed)',
    unnamedDefault: true } ]
```

What UMD (with Rollup.js) does is to change the `export default ...` for this wrapper:

```js
(function(global, factory) {
  typeof exports === "object" && typeof module !== "undefined"
    ? (module.exports = factory())
    : typeof define === "function" && define.amd
    ? define(factory)
    : ((global = global || self), (global.Ola = factory()));
})(this, function() {
  "use strict";

  // CODE HERE

  return Ola;
});
```

There could be two ways AFAIK to implement this with Shrimpit:

1. Pattern (regexp) match this block of code and replace the last `return` for a `export default`.
2. Detect the module.exports match here and use that to find out what is exported. Though,  that is probably difficult/impossible without actually running the code.

I'm trying to use Shrimpit to detect the export from an arbitrary npm module, but it's becoming a lot more difficult than I thought.

**Comment by yamafaktory** [comment]
Hi & thanks for the feedback! Ok, so the idea would be to somehow reverse the UMD exports to ES6 before walking the AST... I would try to see if there's a good way to do that 👍.

**Comment by franciscop** [comment]
Hi thanks, but from my brief experiments it seems that wouldn't be possible without actually running the code, since this is dynamic. Same as module.exports:

```js
if (Math.random() < 0.1) {
  module.exports.abc = "def";
}
```
