### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by alexeychikk** [yamafaktory/shrimpit#133]
It just outputs all the exports. I thought this is the tool for detecting unused ones.

**Comment by yamafaktory** [comment]
Hi @alexeychikk, can you provide more feedback about the issue? The tool should return the unused ones.

**Comment by yamafaktory** [comment]
Closing the issue since I got no more feedback. Feel free to reopen it.

**Comment by stianlp** [comment]
Same thing here. It does not work. Lists all exports in the project, both default exports and named exports.

**Comment by stianlp** [comment]
Found the issue, I have a jsconfig.json specifying a base folder

```
{
  "compilerOptions": {
    "baseUrl": "src"
  },
  "include": ["src"]
}
```

This file makes all imports relative to `src` unless path starts with `../` or `./`.

**Comment by yamafaktory** [comment]
@stianlp Hi and sorry I missed your comment... Your issue is directly related to https://github.com/yamafaktory/shrimpit/issues/27. To make it work what would be needed is a flag to configure the way imports / exports are resolved by the tool.
