### ISSUE TITLE
Need more info on error log

### ISSUE THREAD

**Issue by ipelekhan** [yamafaktory/shrimpit#3]
Hi! First of all, thank you for your work 👍 

I have tried to run shrimpit on a big project with lots of components and the only line I'm getting as a result:
```bash
! SyntaxError: Unterminated JSX contents (17:14)
```

Any suggestions how to track the file name or get more debug info? Thanks in advance.

**Comment by yamafaktory** [comment]
Hi @ipelekhan and thanks for your feedback!

Shrimpit heavily relies on [Babylon](https://github.com/babel/babylon) and the error comes directly from this parser. I can fix it by adding the file name / path to the error (you already get the line number). I will create a new version and get back to you A.S.A.P.

**Comment by yamafaktory** [comment]
@ipelekhan I've just deployed a new version https://github.com/yamafaktory/shrimpit/releases/tag/v0.5.0. Waiting for your feedback!

**Comment by ipelekhan** [comment]
Great! Now error logs are clear enough. Thanks for the hot fix 😃
