### ISSUE TITLE
Default exported class is not picked up correctly

### ISSUE THREAD

**Issue by peterjuras** [yamafaktory/shrimpit#36]
First of all thanks for the great tool! It is really providing a lot of value when cleaning up old code.

I found a bug when exporting classes in the default export:

```js
// a.js
export default class User extends Person {
  walk() {
    console.log("I'm walking");
  }
}
```

```js
// b.js
import User from './a';

new User().walk();
```

shrimpit! Output:
```
 Shrimpit!

 > Files tree

{ '.': null,
  'a.js': { exports: [ 'walk', '/' ], imports: [] },
  'b.js': { exports: [], imports: [ '/' ] } }

 > Unused exports

[ 'walk' ]
```

Expectation: It should not traverse the members of the class declaration, it should simply check whether the "Default" export of a.js is used anywhere.

**Comment by peterjuras** [comment]
Default exports might be broken in general, I see a similar issue for functions:

```js
// a.js
export default function A() {

}
```

```js
// b.js
function B() {

}

export default B;
```

```js
// c.js
function C() {

}

export default C;
```

```js
// d.js
import A from './a';
import B from './b';

A();
B();
```

shrimpit! output:
```
 Shrimpit!

 > Files tree

{ '.': null,
  'a.js': { exports: [ 'A' ], imports: [] },
  'b.js': { exports: [ '/' ], imports: [] },
  'c.js': { exports: [], imports: [ '/' ] },
  'd.js': { exports: [ '/' ], imports: [] } }

 > Unused exports

[ 'A' ]
```
As you can see the B default export is picked up correctly, A however is marked as unused. Even worse, D is not marked as unused, because it appears to be stored as the same import/export path as the default export of B.

**Comment by peterjuras** [comment]
The new version of shrimpit (0.17.0) introduced new behavior, however it still outputs exports that are actually used. Consider the following example:

```js
// a.js
export default function a() { }
```

```js
// b.js
export default class B extends React.Component {
  componentDidMount() { }
  render() { return null; }
}
```

```js
// c.js
import a from './a';
import B from './b';
```

shrimpit output:
```
 Shrimpit!

 > Unused exports

[ { name: 'a', location: 'a.js' },
  { name: 'B', location: 'b.js' },
  { name: 'default (unamed)', location: 'b.js' } ]
```

Expected output:

'a' should be fine because it is imported in c.
Also b should be fine because it is also imported in c.
I'm also not sure why B turns up twice in the output, once as `B` and once as `default (unamed)`

**Comment by yamafaktory** [comment]
@peterjuras the latest release should have fixed the aforementioned issue 🤞, feel free to reopen it if this is not the case (I've moved that comment here as I've initially attached it to the other closed issue 😄)!

**Comment by peterjuras** [comment]
Sadly it appears that version `0.18.1` still did not fix the bug :/

This is the new shrimpit output for my last example. I would expect both a and b to not show up because they are imported in `c.js`

shrimpit output:
```
Shrimpit!

 > Unused exports

[ { location: 'a.js', name: 'a', unnamedDefault: true },
  { location: 'b.js', name: 'B', unnamedDefault: true } ]
```

**Comment by yamafaktory** [comment]
OK, I'll have a look at it again (I thought it was passing yesterday...) 👍.

**Comment by peterjuras** [comment]
Thank you for looking into this. Your module is a game changer when it comes to cleaning up old source code! 🙏

**Comment by yamafaktory** [comment]
@peterjuras Can you please give https://github.com/yamafaktory/shrimpit/releases/tag/v0.18.2 a try? Thanks!

**Comment by peterjuras** [comment]
Thanks, this solved some issues. Now the next issue that I encountered is the following:

```js
// b.js
export default class B {
  test = () => {};
}
```
```js
import B from "./b";
```

Shrimpit output:
```
 Shrimpit!

 > Unused exports

[ { location: 'b.js', name: '/', unnamedDefault: false } ]
```

What is interesting here is that the class property introduces this behavior. If test is written like this:

```js
test() { }
```

no unused export is shown. Do you know where the problem could lie?

**Comment by yamafaktory** [comment]
@peterjuras I've released a new version with a fix https://github.com/yamafaktory/shrimpit/commit/396d16ad913e1ab84666ba37904e8a22a8f6d09c.

Please give it another try and let me know! If this fine, please close the issue. If you encounter another bug, please open a new issue (will be easier to track everything in different threads), thanks a lot 👍.

**Comment by peterjuras** [comment]
Thanks this issue is solved. I encountered a new one, but as you suggested I'll open up a new issue.
