### ISSUE TITLE
Renamed imports lead to unused exports

### ISSUE THREAD

**Issue by peterjuras** [yamafaktory/shrimpit#43]
Example:

```js
// a.js
export const a = {};
```
```js
// b.js
import { a as b } from "./a";
```
shrimpit output:
```
 Shrimpit!

 > Unused exports

[ { location: 'second/a.js', name: 'a', unnamedDefault: false } ]
```

However `a` is actually imported in file b.js.

**Comment by yamafaktory** [comment]
@peterjuras Thanks for the report! I'll take care of this issue and will keep you updated.

**Comment by yamafaktory** [comment]
@peterjuras I've just released a new version https://github.com/yamafaktory/shrimpit/releases/tag/v0.18.7 🚀. Waiting for you feedback! Thanks.

**Comment by peterjuras** [comment]
Thank you, it works now! I also get no more issues for the time being so thank you for all the support! 👍
