### ISSUE TITLE
Support for Flow style type annotations

### ISSUE THREAD

**Issue by seandunn** [yamafaktory/shrimpit#5]
It would be useful to add support for Flow style type annotations (https://flowtype.org/).

**Comment by yamafaktory** [comment]
Hi @seandunn,

Thanks for the feedback. This should be working out of the box (already enabled as a Babylon option, see https://github.com/yamafaktory/shrimpit/blob/master/index.js#L39).

**Comment by yamafaktory** [comment]
Hi @seandunn, should I close this issue or were you expecting something else regarding Flow annotations support?

**Comment by seandunn** [comment]
I'm going to close it as a non-issue @yamafaktory I'll give it another go today but I suspect it's a PBCAK issue. :)
