### ISSUE TITLE
Support node v4.6.x

### ISSUE THREAD

**Issue by nemisj** [yamafaktory/shrimpit#6]
Doesn't work in node v4.6.0 because of
```
class Shrimpit {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

**Comment by yamafaktory** [comment]
Hi @nemisj,

Actually, this is the intended behavior as set in https://github.com/yamafaktory/shrimpit/blob/master/package.json#L28. Not only `Class` will break anyway as the project uses other ES6 features.

Please use a more recent NodeJS version, I suggest to use the excellent [nvm](https://github.com/creationix/nvm).

I'll update the readme to be more clear about that, thanks for the feedback!

**Comment by nemisj** [comment]
Thanks
