### ISSUE TITLE
Glob input?

### ISSUE THREAD

**Issue by benadamstyles** [yamafaktory/shrimpit#93]
Hey, love this. I thought, "I wonder if there's a tool to check for unused exports", and there it was!

I was wondering if you'd accept a PR to change the path input to accept glob patterns instead of direct paths? I've tried to use my shell's glob expansion but it's not expressive enough for what I need.

Thanks!

**Comment by yamafaktory** [comment]
Hey @benadamstyles , I'm glad to hear that this tool is kind of helpful 😄.

Please go ahead with a PR, I'll be happy to merge it into the project 👍!
